gce_name     = "scenario1-vm"
machine_type = "e2-standard-2"
zone         = "us-west1-c"
gce_image    = "ubuntu-os-cloud/ubuntu-2004-lts"
subnet_name  = "demo-subnet2"
custom_sa    = "pro-user@bustling-winter-323317.iam.gserviceaccount.com"
